implement row removal
Web-Dev-Speedrunners/dom-proj pull request #4
Opened 2021-03-08 22:46 UTC by muskankapoor

Capable of removing row of the grid
<img width="516" alt="Screen Shot 2021-03-08 at 5 46 35 PM" src="https://user-images.githubusercontent.com/43054296/110391979-3fafb080-8036-11eb-8154-701beaa5912e.png">

2021-03-09 00:55 UTC, shikdernyc commented
How did you test this? Can you show your test results

2021-03-09 01:00 UTC, shikdernyc requested changes

2021-03-09 01:00 UTC, shikdernyc commented on js/removeRows.js
> +       let removeRow = document.getElementsByTagName('tr')[0]; // reference
What if there are no `tr` elements in the dom.

2021-03-09 01:05 UTC, muskankapoor commented
> How did you test this? Can you show your test results

Hey @shikdernyc just little confused as to what u r asking for. But yes if u press the row remove button then you can see the rows remove in the grid.

2021-03-09 01:11 UTC, shikdernyc commented
> > How did you test this? Can you show your test results
> 
> Hey @shikdernyc just little confused as to what u r asking for. But yes if u press the row remove button then you can see the rows remove in the grid.

> "if u press the row remove button then you can see the rows remove in the grid."

Yeah, that's exactly what I meant. Like just written documentation on how you went about testing it or a gif. 

Since we are not using netlify for pull request preview, I would have to go to my computer, pull up this branch, and then run it. Most reviewers won't do that so it's a good idea to put screenshots of ur changes. Or just go ahead and setup netlify if you have the time.

2021-03-09 01:28 UTC, muskankapoor commented
Hey, @shikdernyc sure. I m having trouble sharing a video here. 
here sharing the before and after screenshots to prove that my code works.
Please approve the pull request thanks! 
<img width="648" alt="Screen Shot 2021-03-08 at 8 23 46 PM" src="https://user-images.githubusercontent.com/43054296/110404375-be174d00-804c-11eb-80c4-67a75bae1ed6.png">
<img width="724" alt="Screen Shot 2021-03-08 at 8 23 53 PM" src="https://user-images.githubusercontent.com/43054296/110404377-bfe11080-804c-11eb-93b5-fe6c99310c59.png">

2021-03-09 01:38 UTC, shikdernyc commented
Looks good to me. There's still another comment I've left in the `js/removeRows.js` file earlier. Can you take a look at that when you get the chance?

2021-03-09 02:46 UTC, muskankapoor commented on js/removeRows.js
> +       let removeRow = document.getElementsByTagName('tr')[0]; // reference
hey, @shikdernyc I thought it was apt to use tr, if you check the populateGrid.js file written by a fellow classmate tr elements is also utilized there, so I think it is fine in this case. 
but if you find any problems in using tr elements then please modify the code as you see. it is in the removeRow branch if you need to see it.

2021-03-09 02:51 UTC, shikdernyc commented on js/removeRows.js
> +       let removeRow = document.getElementsByTagName('tr')[0]; // reference
I mean about the edge case of where there's no more <tr/> element in the dom. For example, if someone continuously clicked on "Remove Row", there would be a point where there's no more `tr` in the web page. In which case, wouldn't `document.getElementsByTagName('tr')[0]` result in `OutOfBound` error?

2021-03-11 02:17 UTC, muskankapoor commented on js/removeRows.js
> +       let removeRow = document.getElementsByTagName('tr')[0]; // reference
Hey @shikdernyc no it doesn't create pronlems for the user if they continously click remove rows. approve this pr so at least we will have the remove row functionality merged into our project.
If I do get a chance (as unfortunately I m away from my laptop today and bit of tomorrow) I will add the error messages and or edge cases later in a separate pr 

Thanks 
Plz approve

2021-03-11 02:52 UTC, shikdernyc commented on js/removeRows.js
> +       let removeRow = document.getElementsByTagName('tr')[0]; // reference
Very well. Lmk when you merge in your PR. I'll merge in my PR afterward and deal with any merge conflicts.

2021-03-11 02:52 UTC, shikdernyc approved these changes

2021-03-11 02:53 UTC, merged

2021-03-11 02:57 UTC, muskankapoor commented on js/removeRows.js
> +       let removeRow = document.getElementsByTagName('tr')[0]; // reference
thanks, @shikdernyc yes just merged in my pr